### ISSUE TITLE
a bug :('<random>', '<random>', 'is') 

### ISSUE THREAD

**Issue by babytdream** [ElliottDyson/OSGA#22]
```
=== persona/prompt_template/v2/generate_obj_event_v1.txt
~~~ persona    ---------------------------------------------------
Arthur Burton 

~~~ gpt_param ----------------------------------------------------
{'engine': 'text-davinci-003', 'max_tokens': 30, 'temperature': 0.2, 'top_p': 0.1, 'stream': False, 'frequency_penalty': 0, 'presence_penalty': 0, 'stop': ['\n']} 

~~~ prompt_input    ----------------------------------------------
['<random>', 'Arthur Burton', 'sleeping', '<random>', '<random>'] 

~~~ prompt    ----------------------------------------------------
Task: We want to understand the state of an object that is being used by someone. 

Let's think step by step. 
We want to know about oven's state. 
Step 1. Sam Johnson is eating breakfast at/using the oven. 
Step 2. Describe the cooking utensils's state: oven is being heated to cook breakfast. 
---
Let's think step by step. 
We want to know about computer's state. 
Step 1. Michael Bernstein is writing email at/using the computer. 
Step 2. Describe the computer's state: computer is being used to write email.
---
Let's think step by step. 
We want to know about sink's state. 
Step 1. Tom Kane is washing his face at/using the sink.
Step 2. Describe the sink's state: sink is running with water.
---
Let's think step by step. 
We want to know about <random>'s state. 
Step 1. Arthur Burton is at/using the sleeping.
Step 2. Describe the <random>'s state: <random> is 

~~~ output    ----------------------------------------------------
Sure! Let's think step by step 

=== END ==========================================================




=== persona/prompt_template/v2/generate_pronunciation_v1.txt
~~~ persona    ---------------------------------------------------
Arthur Burton 

~~~ gpt_param ----------------------------------------------------
{'engine': 'text-davinci-002', 'max_tokens': 15, 'temperature': 0.2, 'top_p': 0.5, 'stream': False, 'frequency_penalty': 0, 'presence_penalty': 0, 'stop': None} 

~~~ prompt_input    ----------------------------------------------
["Sure! Let's think step by step"] 

~~~ prompt    ----------------------------------------------------
Convert an action description to an emoji (important: use two or less emojis). Make sure it's descriptive to the action, like below:

Action description: waking up and starting her morning routine (taking a shower)
Emoji: 🛁🧖‍♀️
Action description: having breakfast (making coffee)
Emoji: ☕️🥐
Action description: painting (turning on classical music to listen to as she paints)
Emoji: 🎨🎵
Action description: exercising (going for a run)
Emoji: 🏃‍♀️
Action description: having breakfast (putting butter on her toast)
Emoji: 🧈🍞
Action description: Sure! Let's think step by step
Emoji: 

~~~ output    ----------------------------------------------------
💡📝 

=== END ==========================================================




WARNING:root:Attempt 1 failed with error: The length of the output was not 2. Retrying...
WARNING:root:Attempt 2 failed with error: The length of the output was not 2. Retrying...
WARNING:root:Attempt 3 failed with error: The length of the output was not 2. Retrying...
WARNING:root:Attempt 4 failed with error: The length of the output was not 2. Retrying...
ERROR:root:Attempt 5 failed with error: The length of the output was not 2. Using failsafe: ('<random>', 'is', 'idle').
=== persona/prompt_template/v2/generate_event_triple_v1.txt
~~~ persona    ---------------------------------------------------
Arthur Burton 

~~~ gpt_param ----------------------------------------------------
{'engine': 'text-davinci-003', 'max_tokens': 30, 'temperature': 0.2, 'top_p': 0.1, 'stream': False, 'frequency_penalty': 0, 'presence_penalty': 0, 'stop': ['\n']} 

~~~ prompt_input    ----------------------------------------------
['<random>', "Sure! Let's think step by step", '<random>'] 

~~~ prompt    ----------------------------------------------------
Task: Turn the input into (subject, predicate, object). 

Input: Sam Johnson is eating breakfast. 
Output: (Dolores Murphy, eat, breakfast) 
--- 
Input: Joon Park is brewing coffee.
Output: (Joon Park, brew, coffee)
---
Input: Jane Cook is sleeping. 
Output: (Jane Cook, is, sleep)
---
Input: Michael Bernstein is writing email on a computer. 
Output: (Michael Bernstein, write, email)
---
Input: Percy Liang is teaching students in a classroom. 
Output: (Percy Liang, teach, students)
---
Input: Merrie Morris is running on a treadmill. 
Output: (Merrie Morris, run, treadmill)
---
Input: <random> is Sure! Let's think step by step. 
Output: (<random>, 

~~~ output    ----------------------------------------------------
('<random>', '<random>', 'is') 

=== END ==========================================================

INFO:root:Adding new action with address: the Ville:Arthur Burton's apartment:kitchen:<random>, duration: 480
Arthur Burton persona.scratch.importance_trigger_curr:: 243
250
aldhfoaf/????
the Ville:Arthur Burton's apartment:kitchen:<random>
Traceback (most recent call last):
  File "/data/OSGA/main/reverie/backend_server/reverie.py", line 472, in open_server
    rs.start_server(int_count)
  File "/data/OSGA/main/reverie/backend_server/reverie.py", line 380, in start_server
    next_tile, pronunciation, description = persona.move(
  File "/data/OSGA/main/reverie/backend_server/persona/persona.py", line 232, in move
    return self.execute(maze, personas, plan)
  File "/data/OSGA/main/reverie/backend_server/persona/persona.py", line 171, in execute
    return execute(self, maze, personas, plan)
  File "/data/OSGA/main/reverie/backend_server/persona/cognitive_modules/execute.py", line 82, in execute
    target_tiles = maze.address_tiles[plan]
KeyError: "the Ville:Arthur Burton's apartment:kitchen"
Error.
```

**Comment by ElliottDyson** [comment]
It seems to be getting <random> as an input from an earlier response? Any chance you could link a file to your full terminal output where this error occurred? Thanks

**Comment by babytdream** [comment]
@ElliottDyson my command is` run 1`(base_the_ville_isabella_maria_klaus). this is output,thanks!
[output.txt](https://github.com/ElliottDyson/OSGA/files/12700869/output.txt)

**Comment by ElliottDyson** [comment]
> same question. any progress?

Still working on it, among other things. Unfortunately, I seem to be the only person working on active development at this time, so I'm afraid fixes and improvements are probably taking longer than you might be used to. However, be rest assured, as I said above, I am working on this. Thank you

**Comment by abhimalamkar** [comment]
This was resolved!
